[#section-1]
== Introduction

[#section-why-this-guide]
=== Why this guide?
 
Camera traps have emerged as a powerful technology for the semi-automated monitoring of natural ecosystems. Their success has led to an exponential growth of camera trap data worldwide. Herein lies a major challenge: large volumes of data are waiting to be classified, interpreted and archived. Data management, rather than data collection, has become a limiting factor for camera trap research. The proliferation of camera trap projects has also led to a diversity of terminologies, classification methods and data management practices, which impedes transparency, interoperability, cross-project collaboration or meta-analyses. A large, interconnected network of remote cameras could act as an instrument for reliable, real-time biodiversity management and decision making, but if we are not able to combine data, camera trap research will lose its full potential. This is why camera trap data needs to be open and FAIR (findable, accessible, interoperable and reusable, see citenp:[wilkinson-2016]), so that both humans and machines can use this valuable data for present and future applications.

To optimize the (re)use of camera trap data, there is a need for best practice guidelines. Several guides exist that tackle one or more elements of the camera trap research life cycle: planning, technology and techniques, study design, data collection, analysis, data management methods and data publication cite:[oconnell-2011,rovero-2013,meek-2014,cadman-2014,burton-2015,wearn-2017]. Since then, the camera trapping community has made significant progress:

* Specialized data management platforms are now primarily used to manage projects and data
* <<AI,Artificial intelligence>> (AI) and <<cloud-computing,cloud computing>> are increasingly used to automate <<species-recognition,species recognition>> and will soon be applied to most recorded media
* Data exchange is now facilitated by Camtrap DP, a <<data-exchange-format,data exchange format>> developed under Biodiversity Information Standards (TDWG). There is increased awareness of open science, <<FAIR>> data cite:[wilkinson-2016] and privacy regulations

No up-to-date guidelines are available that focus on camera trap data management and publication only. This guide aims to fill that gap.

[#section-target-audience]
=== Target audience

This guide is intended to be useful for anyone managing a camera trap study. The specific focus on data management and publication makes this best practice guide extra useful for profiles such as data stewards, data publishers, database and information managers and students working with biodiversity informatics.

The authors of this guide have experience with traditional camera traps designed for terrestrial medium-to-large terrestrial mammals, but many of the recommendations (as well as the <<camtrap-dp,Camtrap DP>> standard) should be applicable to data from other camera trap types.

[#section-what-this-guide-is-not-about]
=== What this guide is not about

This guide primarily focuses on the management, quality control, enhancement and publication of camera trap data. The following topics are out of scope:

* Planning a camera trap study:  types of camera traps,  study design,  etc.
* Camera trap deployment and collection: field work, baits and lures, data retrieval, etc. 
* Analysis: software for analysis, ecological modelling, bias correction, etc.

Many extensive guides on these topics are already available. See <<table-aims>> and <<table-topics>> for a brief overview.

<<<
