[[intro]]
== Introduction

=== Why this guide?
 
Camera traps have emerged as a powerful tool to monitor the state of natural ecosystems. This resulted in the improvement of technology and techniques for camera trapping research, which brought along an explosion of camera trap data. Herein lies a major challenge: large volumes of data are waiting to be classified, interpreted and archived. Data management, rather than data collection, is now becoming a limiting factor in camera trap research. Additionally, the proliferation of camera trap projects led to a diversity of terminologies, classification methods and data management practices. This has led to a lack of accessibility and transparency, resulting in limited cross-project collaboration or meta-analyses. A large, interconnected network of remote cameras can act as an instrument for reliable, real-time biodiversity management and decision making. If we’re not able to merge data from different projects together, camera trap research will lose its full potential.

To optimize the (re)use of camera trap data, there’s a need for best practice guidelines. Several guides exist that tackle one or more elements of the camera trap research life cycle: planning, technology and techniques, study design, data collection, analysis, data management methods and data publication (#cit_oconnell_2011, #cit_rovero_2013, #cit_meek_2014, #cit_cadman_2014, #cit_burton_2015, #cit_wearn_2017). Since then, the camera trapping community has made significant progress:

* Specialized data management platforms are now primarily used to manage projects and data
* <<ai,Artificial intelligence>> (AI) and <<cloud-computing,cloud computing>> are increasingly used to automate <<species-recognition,species recognition>> and will soon be applied to most recorded media
* ata exchange is now facilitated by Camtrap DP, a <<data-exchange-format,data exchange format>> developed under Biodiversity Information Standards (TDWG).There is increased awareness of open science, <<fair,FAIR>> data (#cit_wilkinson_2018) and privacy regulations

No up-to-date guidelines are available that focus on camera trap data management and publication only. This guide aims to fill that gap.

=== How to read this guide?

This guide aims to cover all aspects related to the management and publication of camera trap data. Depending on your prior experience and your interest in reading this guide, each (sub)chapter may be consulted independently. At the start of this guide, we summarize the most important take-home messages (#chapter_general_recommendations). This is intended for readers interested in general guidance only. Each chapter afterwards starts with its own recommendations and ends with references to  relevant literature for further exploration on the topic. At the very end of this guide, there’s a #chapter_glossary to assist the reader in understanding what each concept introduced in this guide actually means. 
Underlined terms throughout this guide link to definitions in the #chapter_glossary. Monospaced text refers to terms, variables or functions (e.g. `dwc:scientificName` or `write_dwc()`).

=== Target audience

This guide is intended to be useful for anyone managing a camera trap study. The specific focus on data management and publication makes this best practice guide extra useful for profiles such as data stewards, data publishers, database and information managers and students working with biodiversity informatics. 

=== What this guide is not about

This guide primarily focuses on the management, quality control, enhancement and publication of camera trap data. This following topics are out of scope:

* Technical aspects of camera traps: types of camera traps, camera settings, etc.
* Study design: how to distribute and position camera traps for your research question, effect of bait use, etc.
* Study execution: field work, data retrieval, etc.
* Statistical analysis: software for analysis, ecological modeling, bias correction, etc.

Many extensive guides on these topics are already available. See #chapter_two for a brief overview.
