[#section-1]
== Introduction

[#section-why-this-guide]
=== Why this guide?
 
Camera traps have emerged as a powerful tool to monitor the state of natural ecosystems. This resulted in the improvement of technology and techniques for camera trap research, which brought along an explosion of camera trap data. Herein lies a major challenge: large volumes of data are waiting to be classified, interpreted and archived. Data management, rather than data collection, is now becoming a limiting factor in camera trap research. Additionally, the proliferation of camera trap projects led to a diversity of terminologies, classification methods and data management practices. This has led to a lack of accessibility and transparency, resulting in limited cross-project collaboration or meta-analyses. A large, interconnected network of remote cameras can act as an instrument for reliable, real-time biodiversity management and decision making. If we’re not able to merge data from different projects together, camera trap research will lose its full potential. This is why we need open and FAIR (findable, accessible, interoperable and reusable, cite:[wilkinson-2016]) camera trap data: we need to find, access, understand, merge and reuse the data. By making the data open and FAIR, both humans and machines are able to use this valuable data for present and future applications.

To optimize the (re)use of camera trap data, there’s a need for best practice guidelines. Several guides exist that tackle one or more elements of the camera trap research life cycle: planning, technology and techniques, study design, data collection, analysis, data management methods and data publication cite:[oconnell-2011,rovero-2013,meek-2014,cadman-2014,burton-2015,wearn-2017]. Since then, the camera trapping community has made significant progress:

* Specialized data management platforms are now primarily used to manage projects and data
* <<AI,Artificial intelligence>> (AI) and <<cloud-computing,cloud computing>> are increasingly used to automate <<species-recognition,species recognition>> and will soon be applied to most recorded media
* Data exchange is now facilitated by Camtrap DP, a <<data-exchange-format,data exchange format>> developed under Biodiversity Information Standards (TDWG). There is increased awareness of open science, <<FAIR>> data cite:[wilkinson-2016] and privacy regulations

No up-to-date guidelines are available that focus on camera trap data management and publication only. This guide aims to fill that gap.

[#section-target-audience]
=== Target audience

This guide is intended to be useful for anyone managing a camera trap study. The specific focus on data management and publication makes this best practice guide extra useful for profiles such as data stewards, data publishers, database and information managers and students working with biodiversity informatics.

[#section-what-this-guide-is-not-about]
=== What this guide is not about

This guide primarily focuses on the management, quality control, enhancement and publication of camera trap data. The following topics are out of scope:

* Planning a camera trap study:  types of camera traps,  study design,  etc.
* Camera trap deployment and collection: field work, baits and lures, data retrieval, etc. 
* Analysis: software for analysis, ecological modelling, bias correction, etc.

Many extensive guides on these topics are already available. See <<table-aims>> and <<table-topics>> for a brief overview.

<<<
