[[chapter_three]]

== Managing camera trap data

*HIGHLIGHTS*

* Add highlights here
* Add highlights here
* Add highlights here

Once a camera trap is operative in the field, it can generate hundreds, thousands or even millions of pictures or videos in the timeframe of the project. 
Ultimately, these data need to be analysed. But first, data need to be retrieved, stored, organized and labelled. 
The content of the images needs interpretation or annotation, either manually or facilitated by technology. 
All these steps are considered in the data management process.

Data management is one of the real bottlenecks in camera-trapping research <<ref_bubnicki_2013>>. 
The massive amount of information stored on memory cards requires a high investment in terms of manpower and time. 
If data storage and classification is lagging behind, large volumes of data will remain unused and will get lost eventually. 
Manual extraction, organization and labelling can introduce human errors and can lead to data loss. 
In addition, there’s often more information in the image or video than the sole target species (group) or topic that is the focus of the project. 
Camera traps inherently detect multiple species and observations of nontarget species provide valuable data for other research objectives. 
If all data, including non target species, were annotated, more relevant outcomes to funds could be generated (<<ref_young_2018>>, <<ref_wearn_2017>>).

To conclude, every researcher should pay attention to data hygiene. The underlying idea is: rather have ten well-documented elements, 
rather than a hundred poorly documented ones. Only in this way can we turn the cacophony of raw image data into useful quantitative data.

In this chapter, we introduce a number of general conventions for sound data management data. 
We zoom deeper into what camera trap data exactly is. For each type of camera trap data 
(<<#project-metadata, metadata>>,<<#media-files, media>>, <<deployments>>, <<observations>>), we focus on how to best manage these, and what data management platforms you can use to facilitate you in doing so.

=== What are camera trap data

Intuitively, we associate camera trap data with the <<media>> files captured by the <<camera,cameras>>. 
But to be able to use these for research they need to be documented with additional information. 
Media files should be <<classified>> to know what species were observed. Information on camera <<deployment>>, duration, <<location>>, <<alignment>> and sampling methodology 
is needed to know when, where and how likely those species were to be observed. 
Finally, we need information about the <<project,project/study>> as a whole to know the scope and who was involved.

=== Project Metadata

==== Participants and roles

=== Media files

==== Timestamps

==== File naming

==== Storage

=== Deployments

==== Column naming

==== Location

==== Camera model, settings and alignment

==== Deployment groups

==== Covariates

=== Observations

==== Classification

==== Citizen science

==== Artificial intelligence

==== Media or event based classification

==== Common or scientific names

=== Data management systems

