[[chapter_three]]

== Managing camera trap data

*HIGHLIGHTS*

* Add highlights here
* Add highlights here
* Add highlights here

Once a camera trap is operative in the field, it can generate hundreds, thousands or even millions of pictures or videos in the timeframe of the project. 
Ultimately, these data need to be analysed. But first, data need to be retrieved, stored, organized and labelled. 
The content of the images needs interpretation or annotation, either manually or facilitated by technology. 
All these steps are considered in the data management process.

Data management is one of the real bottlenecks in camera-trapping research <<ref_bubnicki_2013>>. 
The massive amount of information stored on memory cards requires a high investment in terms of manpower and time. 
If data storage and classification is lagging behind, large volumes of data will remain unused and will get lost eventually. 
Manual extraction, organization and labelling can introduce human errors and can lead to data loss. 
In addition, there’s often more information in the image or video than the sole target species (group) or topic that is the focus of the project. 
Camera traps inherently detect multiple species and observations of nontarget species provide valuable data for other research objectives. 
If all data, including non target species, were annotated, more relevant outcomes to funds could be generated (<<ref_young_2018>>, <<ref_wearn_2017>>).

To conclude, every researcher should pay attention to data hygiene. The underlying idea is: rather have ten well-documented elements, 
rather than a hundred poorly documented ones. Only in this way can we turn the cacophony of raw image data into useful quantitative data.

In this chapter, we introduce a number of general conventions for sound data management data. 
We zoom deeper into what camera trap data exactly is. For each type of camera trap data 
(<<project-metadata, metadata>>, <<media-files, media>>, <<deployments, deployments>>, <<observations, observations>>), we focus on how to best manage these, and what data management platforms you can use to facilitate you in doing so.

=== What are camera trap data

Intuitively, we associate camera trap data with the <<media>> files captured by the <<camera,cameras>>. 
But to be able to use these for research they need to be documented with additional information. 
Media files should be <<classified>> to know what species were observed. Information on camera <<deployment>>, duration, <<location>>, <<alignment>> and sampling methodology 
is needed to know when, where and how likely those species were to be observed. 
Finally, we need information about the <<project,project/study>> as a whole to know the scope and who was involved.

Overall, we can distinguish four types of camera trap data:

* **Project metadata:** information about the camera trap project/study as a whole
* **Media files:** images, videos or sound files captured by the <<camera,cameras>>, including their <<EXIF>> metadata
* **Deployments:** information regarding the camera <<location>> and <<alignment>>, the sampling duration and <<covariates>>. Typically not automatically registered by the camera.
* **Observations:** information regarding what can be seen or heard on the media files (i.e. objects of interest), such as animals, humans or vehicles. The aim is typically to record what animal species were observed, optionally including information on their group size, life stage, sex and behaviour.

These data can be organized in different ways, based on personal preference or what <<data-management-system,data management system>> is used. 
We can however identify a number of core concepts, hereafter referred to as classes, that constitute a “model” for camera trap data (see #figure_classes). 
Those classes are project, organization, participant, deployment, location, device, media, sequence and observation.

FIGURE CLASSES HERE

=== Project Metadata

Project metadata document a camera trap project/study as a whole. Who was involved, what was the rationale, what sampling methods were used and what was the scope? 
Projects can vary a lot in size and are sometimes part of meta-studies or subdivided in subprojects to better manage their hundreds of thousands of deployments (e.g. https://www.snapshot-usa.org/[Snapshot USA]). 
Describe projects at a level that makes sense. Is it possible to identify a person that can make decisions or answer questions about the project? 
How easy is it to describe the methodology? If the answer to those questions is no, then it might be better to consider those separate projects. 
Also note that we strongly recommend publishing data at project level, i.e. one dataset for one project (see <<chapter_four, chapter 4>>).

When published, project metadata are a substantial part of the dataset metadata (see #figure_metadata), allowing others to discover your dataset when searching for certain keywords and assess if it fits their research needs. 
When describing your project, think about what others would need to understand it. We recommend to cover the following aspects:

* Title
* Identifier and/or acronym
* Description (including rationale)
* Contributors and their roles (including organizations)
* Sampling design (simple random, systematic random, etc.)
* Capture method (motion detection and/or timelapse)
* Whether individual animals were tracked
* Geographic scope
* Temporal scope
* Taxonomic scope
* Link to website
* Keywords
* Funding

Data management systems typically organize this information into the following classes: 
<<project>>, <<subproject>>, <<organization>> and <<participant>> (see #figure_classes).

FIGURE METADATA HERE

==== Participants and roles

A <<participant>> is a person associated with a camera trap project. Information typically captured about a participant is their first name, last name, email, and ORCID. 
The role(s) of a participant is defined in relation to a project (e.g. principal investigator, contact person) and organization (e.g. researcher) (see #figure_classes). 
Different names are used for similar roles. We recommend simplifying those to a limited set of controlled values (e.g. Camtrap DP roles) when publishing data (see #table_roles).

[cols=7*,options="header"]
|===
|Camtrap DP
|CTMS <<ref_forrester_2017>>
|Wildlife camera metadata protocol <<ref_protocol_2019>>
|Datacite <<ref_datacite>>
|EML <<ref_eml_2015>>
|Agouti <<ref_agouti_2019>>
|Wildlife Insights <<ref_wildlife_insights>>

|contact
|ProjectContact
|Project Coordinator
|ContactPerson
|Point of Contact
|Project coordinator
|Project Owner

|principalInvestigator
|PrincipalInvestigator
|
|ProjectLeader
ProjectManager
Supervisor
|Owner
Principal Investigator
|Principal investigator
|Project Owner

|rightsHolder
|
|
|RightsHolder
|
|
|

|publishers
|
|
|Distributor
|Distributor
Publisher
|
|

|contributor
|sequenceIdentifiedBy
PhotoTypeIdentifiedBy
|Crew Member
Surveyor
|DataManager
DataCurator
DataCollector
ProjectMember
Researcher
|Curator
Editor
Author
Content Provider
Originator
|Admin
Taxonomic expert
Photo processor
Volunteer
|Project Editor
Project Contributor
Project Tagger

|
|
|
|Other
|User
Processor
Reviewer
Metadata Provider
|View only
Dummy
Awaiting access
|Project Viewer

|=== 



=== Media files

==== Timestamps

==== File naming

==== Storage

=== Deployments

==== Column naming

==== Location

==== Camera model, settings and alignment

==== Deployment groups

==== Covariates

=== Observations

==== Classification

==== Citizen science

==== Artificial intelligence

==== Media or event based classification

==== Common or scientific names

=== Data management systems

