[#section-4]
== Publishing camera trap data

[#section-darwin-core]
=== Darwin Core

[#table-dwc-occurrence-core]
.Recommended terms to use when expressing camera trap data as a Darwin Core Occurrence core. Source for example values: https://tdwg.github.io/camtrap-dp/example/00a2c20d/#79204343
[%header,cols=3*]
|===
|Term
|Status
|Example value

|<<section-type,type>>
|Share if available
|StillImage

|<<section-license,license>>
|Share if available
|[.break-all]#https://creativecommons.org/publicdomain/zero/1.0/legalcode#

|<<section-rightsholder,rightsHolder>>
|Share if available
|INBO

|<<section-datasetid-datasetname,datasetID>>
|Share if available
|[.break-all]#https://doi.org/10.15468/5tb6ze#

|<<section-collectioncode,collectionCode>>
|Share if available
|Agouti

|<<section-datasetid-datasetname,datasetName>>
|Share if available
|Sample from: MICA - Muskrat and coypu camera trap observations in Belgium, the Netherlands and Germany

|<<section-basisofrecord,basisOfRecord>>
|Required
|MachineObservation

|<<section-informationwithheld,informationWithheld>>
|Share if available
|

|<<section-datageneralizations,dataGeneralizations>>
|Share if available
|coordinates rounded to 0.001 degrees

|<<section-occurrenceid,occurrenceID>>
|Required
|05230014

|<<section-individualcount,individualCount>>
|Strongly recommended
|1

|<<section-sex,sex>>
|Share if available
|

|<<section-lifestage,lifeStage>>
|Share if available
|adult

|<<section-behavior,behavior>>
|Share if available
|

|<<section-occurrencestatus,occurrenceStatus>>
|Strongly recommended
|present

|<<section-occurrenceremarks,occurrenceRemarks>>
|Share if available
|

|<<section-organismid,organismID>>
|Share if available
|

|<<section-eventid,eventID>>
|Strongly recommended
|79204343

|<<section-parenteventid,parentEventID>>
|Strongly recommended
|00a2c20d

|<<section-eventdate,eventDate>>
|Required
|[.break-all]#2020-06-12T04:04:29Z/2020-06-12T04:04:55Z#

|<<section-habitat,habitat>>
|Share if available
|Campine area with a number of river valleys with valuable grasslands

|<<section-samplingprotocol,samplingProtocol>>
|Strongly recommended
|camera trap

|<<section-samplingeffort,samplingEffort>>
|Share if available
|[.break-all]#2020-05-30T02:57:37Z/2020-07-01T09:41:41Z#

|<<section-eventremarks,eventRemarks>>
|Share if available
|camera trap without bait near game trail \| tags: position:above stream

|<<section-locationid,locationID>>
|Share if available
|e254a13c

|<<section-locality,locality>>
|Share if available
|B_HS_val 2_processiepark	

|<<section-decimallatitude-decimallongitude,decimalLatitude>>
|Strongly recommended
|51.496

|<<section-decimallatitude-decimallongitude,decimalLongitude>>
|Strongly recommended
|4.774

|<<section-geodeticdatum,geodeticDatum>>
|Strongly recommended
|EPSG:4326

|<<section-coordinateuncertaintyinmeters,coordinateUncertaintyInMeters>>
|Strongly recommended
|187

|<<section-coordinateprecision,coordinatePrecision>>
|Share if available
|0.001

|<<section-identifiedby,identifiedBy>>
|Share if available
|Peter Desmet

|<<section-dateidentified,dateIdentified>>
|Share if available
|2023-02-02T13:57:58Z

|<<section-identificationremarks,identificationRemarks>>
|Share if available
|classified by human

|<<section-taxonid,taxonID>>
|Share if available
|GCHS

|<<section-scientificname,scientificName>>
|Required
|Ardea cinerea

|<<section-kingdom,kingdom>>
|Strongly recommended
|Animalia

|<<section-vernacularname,vernacularName>>
|Share if available
|grey heron

|===

[#section-type]
==== type

https://dwc.tdwg.org/list/#dc_type[dc:type]

The nature of the resource. Use `StillImage` if the record is based on an image or sequence of images, `MovingImage` if based on a video. One can also use the broader term `Image` for all records.

[#section-license]
==== license

https://dwc.tdwg.org/list/#dcterms_license[dcterms:license]

The licence under which the data record is shared. Very likely this will be the same licence as the one used for the dataset as a whole, but it is possible to deviate cite:[waller-2020]. To enable wide use, we recommend publishing data under a Creative Commons Zero waiver and to provide it as a URL: `https://creativecommons.org/publicdomain/zero/1.0/legalcode`. In Camtrap DP, this term corresponds with the licence that has the scope `data` in {package-licenses}.

[#section-rightsholder]
==== rightsHolder

https://dwc.tdwg.org/list/#dcterms_rightsHolder[dcterms:rightsHolder]

The person or organization (i.e. <<participant>>) owning or managing rights over the resource. In all likeness the organization that decided under what license the data are published and/or the publisher of the data (i.e. the organization selected as publisher when registering a dataset with GBIF). Use an acronym if the organization has one. In Camtrap DP, this term corresponds with the collaborator that has the role `rightsHolder` in {package-contributors}.

[#section-datasetid-datasetname]
==== datasetID & datasetName

term:dwc[dwc:datasetID] & term:dwc[dwc:datasetName]

Respectively the identifier and name of the dataset. For term:dwc[dwc:datasetID] we recommend using a stable URL or identifier that allows users to find information about the source dataset/study. In order of preference: dataset DOI (`https://doi.org/10.15468/5tb6ze`), study URL (`http://n2t.net/ark:/63614/w12001317`), or study identifier used by the <<data-management-system,data management system>>. In Camtrap DP, this term corresponds with {package-id}, unless a better identifier is available (e.g. a DOI).

term:dwc[dwc:datasetName] should refer to the title of the dataset/study as referred to by term:dwc[dwc:datasetID]. We recommend using the same value for the title in the metadata. In Camtrap DP, this term corresponds with {package-title}.

[#section-collectioncode]
===== collectionCode

term:dwc[dwc:collectionCode]

The name or acronym identifying the collection or dataset the record was derived from. Traditionally used to indicate a physical collection, we recommend to provide the name of the <<data-management-system,data management system>> (i.e. virtual collection) the record was derived from. This allows users to search for records from the same data management system across datasets. Recommended values: `Agouti, `Camelot`, `eMammal`, `Trapper`, `Wildlife Insights`, etc. In Camtrap DP, this term corresponds with the `title` of the (applicable) source in {package-sources}.

[#section-basisOfRecord]

term:dwc[dwc:basisOfRecord]

The specific nature of the record. Set to `MachineObservation` for all records.

[#section-sex]
==== sex

term:dwc[dwc:sex]

The sex of the observed individual(s). We recommend using the controlled values `male` and `female`, which are based on Camtrap DP and compatible with the <<https://rs.gbif.org/vocabulary/gbif/sex.xml,GBIF Sex vocabulary>>. In Camtrap DP, this term corresponds with {observations-sex}.

[#section-lifestage]
==== lifeStage

term:dwc[dwc:lifeStage]

The life stage of the observed individual(s). We recommend using the controlled values `adult`, `subadult`, and `juvenile`, which are based on Camtrap DP and compatible with the <<https://registry.gbif.org/vocabulary/LifeStage,GBIF LifeStage vocabulary>>. In Camtrap DP, this term corresponds with {observations-lifeStage}.

[#section-behavior]
==== behavior

term:dwc[dwc:behavior]

The dominant behaviour of the observed individual(s). We recommend using existing or your own controlled values (e.g. grazing, browsing, rooting, vigilance, running, walking). In Camtrap DP, this term corresponds with {observations-behavior}.

[#section-occurrencestatus]
==== occurrenceStatus

term:dwc[dwc:occurrenceStatus], *share if available*

A statement about the presence or absence of the taxon at a location. Following the recommendations in this document, camera trap datasets only contain presence records. Set to `present` for all records.
